### ISSUE TITLE
4 versiones

### ISSUE THREAD

**Issue by levhita** [LulyAtilano/Kitten#3]
Por la forma de manejar las mediaquerys, se generaron 4 versiones, en lugar de 3.

![image](https://user-images.githubusercontent.com/225066/41614139-4ad62f3a-73bd-11e8-915b-8f9f1e363f0d.png)

![image](https://user-images.githubusercontent.com/225066/41614151-5159204c-73bd-11e8-8569-d6dfa241f32c.png)

![image](https://user-images.githubusercontent.com/225066/41614161-57b2ec5c-73bd-11e8-9183-4980523dde96.png)
![image](https://user-images.githubusercontent.com/225066/41614179-61c798dc-73bd-11e8-9302-da173106075a.png)

**Comment by LulyAtilano** [comment]
ya se arreglaron los medias queries, para que sólo se presenten dos versiones dejando la mobile como default.
